# Run in this directory with command: docker-compose up
# Stop with command: docker-compose stop
# Rebuild (to refresh cached image) with: docker-compose build --no-cache

web1:
  build: .
  ports:
    - 8080:80

web2:
  build: .
  ports:
    - 8081:80

web3:
  build: .
  ports:
    - 8082:80
